package org.wildflyjpa.model;
// Generated 06.08.2017 15:43:53 by Hibernate Tools 5.2.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Mytable generated by hbm2java
 */
@Entity
@Table(name = "mytable", catalog = "mydb")
@XmlRootElement
public class Mytable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4375342243881450123L;
	private int id;
	private String name;

	public Mytable() {
	}

	public Mytable(int id) {
		this.id = id;
	}

	public Mytable(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
